lang = {
    SKU: 'SKU',
    Title: '名称',
    Status: '状态',
    Weight: '重量',
    Accessories: '配件',
    Image: '图片',
    Stock: '库存',
    Position_Management: '仓位管理',
    Position: '仓位',
    Packaging_Materials: '包材',
    No: '编号',
    Qty: '数量',
    Search: '查询',
    Save: '保存',
    Create:'创建',
    Update:'更新',
    Upload:'上传',
    Close:'关闭',
    Prompt:'提示',
    Confirmation: '确认',
    Waitting: '正在加载中,请稍候.',
    Warning: '警告',
    Success: '成功',
    Failure: '错误',
    Network_Error: '网络错误,请稍后再试.',
    SKU_Is_Empty: 'SKU 为空!'
}