lang = {
    Waitting:'数据正在加载中,请稍后...',
    Failure:'失败',
    Network_Error:'网络错误',
    Research_System:'调研系统',
    Search_Panel:'查询面板',
    ID:'序号',
    Created_On:'录入时间',
    Warehouse:'仓库',
    Warehouse_Array:[[0, 'SZ'],[1, 'UK']],
    Site:'站点',
    Site_Array:[[0, 'US'],[1, 'UK'],[2, 'AU']],
    English_Keyword:'英文关键字',
    Chinese_Title:'中文标题',
    Sales:'销售员',
    Status:'状态',
    Modified_On:'修改时间',
    Reason:'原因',
    Images:'图片',
    Category:'分类',
    Category_Array:[[0, 'Cell Phone & PDAS'],[1, 'Computers & Networking'],[2, 'Consumer Electronic'],[3, 'Cameras & Photos'],[4, 'Bussiness & Industry'],[5, 'Home & Garden'],[6, 'Musical Instruments'],[7, 'Jewelry & Watches'],[8, 'Pet Suppliers'],[9, 'Baby'],[10, 'Sporting Goods'],[11, 'Travel'],[12, 'Toys & Hobbies'],[13, 'Health & Beauty'],[14, 'ebay motor']],
    Cancel_Reason:'取消原因',
    Search:'查询',
    Reference_Links_1:'参考链接1',
    Reference_Links_2:'参考链接2',
    Reference_Links_3:'参考链接3',
    Reference_Links_4:'参考链接4',
    Development_Standards:'开发标准',
    Development_Standards_Array:[['A1', 'A1'],['A2', 'A2'],['A3', 'A3'],['B', 'B'],['C1', 'C1'],['C2', 'C2'],['C3', 'C3']],
    Specific_Data:'具体数据',
    MarketPlace_Average_Price:'市场平均价',
    MarketPlace_Min_Price:'市场最低价',
    Target_Sales_Price:'目标销售价',
    Target_Month_Sales:'目标月销量',
    Target_Total_Cost:'目标总成本',
    Target_Purchase_Cost:'目标采购成本',
    Plans_Sales_Mode:'计划销售方式',
    Estimated_Weight:'预估重量(kg)',
    Product_Parameter_Information:'产品参数信息',
    Product_Photo_Gallery:'产品图片展示',
    Submit:'提交',
    Update:'更新',
    Edit:'编辑',
    Update_Success:'更新成功.',
    Add_Success:'添加成功',
    Close:'关闭',
    Warning:'警告',
    Message:'消息',
    Waiting:'正在加载,请等待.',
    User_Password_Error:'用户名或密码错误!',
    Status_Panel:'状态面板',
    
    Purchaser:'采购员',
    Product_Cost:'产品成本',
    Product_Net_Weight:'产品净重(kg)',
    Min_Purchase_Num:'最小起订数',
    Product_Arrival_Days:'到货天数',
    Remark:'备注',
    Suppliers_Info:'供应商信息',
    
    User_Name:'用户名',
    Password:'密码',
    
    Add_New_Product:'添加新品',
    New_Product:'新品',
    Waiting_Review:'待审核',
    Waiting_Inquiry:'待询价',
    Waiting_Inquiry_Review:'询价待审核',
    Inquiry_Complete:'询价完成',
    Take_Sample_Confirm:'拿样确认',
    New_Product_Develop_Success:'新品开发成功',
    New_Product_Develop_Failure:'新品开发失败',
    Give_Up:'放弃',
    Status_Array: ['新品', '待审核', '待询价',
                   '询价待审核', '询价完成', '拿样确认',
                   '新品开发成功', '新品开发失败', '放弃'],
    Plans_Sales_Mode_Array: [[0,'拍卖'], [1,'一口价'], [2,'拍卖&一口价'], [3,'议价']]
}