lang = {
    SKU: 'SKU',
    Title: '标题',
    Min_Purchase_Num: '最小采购数',
    Purchase_In_The_Way: '采购在途',
    Suggest_Purchase_Num: '建议采购数',
    Stock: '库存',
    Safe_Stock: '安全库存',
    Virtual_Stock: '虚拟库存',
    Stock_Days: '采购周期',
    Three_Day_Flow: '三天流量',
    One_Week_Flow: '第一周流量',
    Two_Week_Flow: '第二周流量',
    Three_Week_Flow: '第三周流量',
    Purchase_Cycle: '采购周期',
    Sku_Min_Purchase_count: '最小采购数',
    Status: '状态',
    Type: '类型',
    Purchase_Planned_Type: '采购计划类型',
    Purchase_Planned_Generate_Time: '采购计划生成时间',
    Purchase_Status: '采购状态',
    Search: '查询',
    Purchase_Planned_Type_Enum: {all: '所有', normal: '自动', manual: '手动'},
    Purchase_Status_Enum: {all: '所有', normal: '自动', manual: '手动'},
    Create_Purchase_Orders: '创建采购订单',
    Add_Purchase_Planned: '添加采购计划',
    
    Purchase_Orders_Id: '采购订单号',
    Purchase_Orders_Type: '采购订单类型',
    Purchase_Orders_Status: '采购订单状态',
    Purchase_Orders_Status_Enum: {draft: '草稿', waiting_inquiry: '待询价', waiting_approval: '待审核', approval_not_pass: '审核未通过', approval_pass: '审核通过', in_transit: '采购在途', change_to_go: '转为入库单'},
    Purchaser: '采购者',
    Vendors: '供应商',
    Vendors_Phone: '供应商电话',
    Vendors_Fax: '供应商传真',
    Contacts: '联系人',
    Office_Phone: '办公室电话',
    Mobile_Phone: '移动电话',
    Payment_Method: '付款方法',
    Receive_Accounts: '收款账户',
    Address: '地址',
    WebSite: '站点',
    
    Generate_Purchase_Orders_Date: '下采购订单',
    Approval_Pass_Date: '审核通过',
    Expected_Arrival_Date: '预计到货',
    Sku: 'SKU',
    Sku_Status: 'SKU 状态',
    Sku_Title: 'SKU 名称',
    Sku_Accessories: 'SKU 配件',
    Sku_Stock: 'SKU 库存',
    Sku_Virtual_Stock: 'SKU 虚拟库存',
    Sku_Purchase_In_Transit: '采购在途',
    Sku_Arrival_Qty: '到货数',
    Sku_No_Arrival_Qty: '未到货数',
    Sku_Purchase_Qty: '采购个数',
    Sku_Old_Purchase_Qty: '原采购个数',
    Sku_Purchase_Qty_Remark: '采购个数备注',
    Sku_Price: '单价',
    Sku_Old_Price: '原单价',
    Sku_Price_Remark: '单价备注',
    Sku_Total_Price: '总价',
    SKU_Purchase_Cycle: 'SKU 采购周期',
    SKU_Three_Day_Flow: 'SKU 三天流量',
    SKU_Week_Flow: 'SKU 一周流量',
    Sku_Defective_Qty: 'SKU 不良品仓',
    Sku_Rework_Qty: 'SKU 返修仓',
    Remark: '备注',
    Created_By: '创建者',
    Created_On: '创建时间',
    Category:'分类',
    Import_Purchase_Orders: '导入采购订单',
    Export_Purchase_Orders: '导出',
    Import_Purchase_Orders_Excel: '导入Excel文件转化为采购订单',
    File: '文件',
    Select_An_Excel_File: '选择一个Excel文件',
    Edit_Purchase_Orders:'编辑采购订单',
    Show_Remark:'显示备注',
    Submit_Purchase_Orders:'提交采购订单',
    Purchase_Orders_Inquiry_Complete:'询价完成',
    Purchase_Orders_Approval_Pass:'审核通过',
    Purchase_Orders_Approval_Not_Pass:'审核未通过',
    Purchase_Orders_Return_Approval: '反审核',
    Delete_Purchase_Orders: '删除采购订单',
    Delete_selected_Purchase_Orders: '删除选中的采购订单?',
    Go_Inventory_Orders:'采购入库单',
    Go_Inventory_Orders_Status:'入库单状态',
    Go_Inventory__Date:'入库时间',
    Go_Inventory_Start_Date:'入库起始时间',
    Go_Inventory_End_Date:'入库结束时间',
    Purchase_Orders_To_Go_Inventory_Orders:'采购订单转入库单',
    Go_Inventory_Orders_To_Inventory:'采购入库单入库',
    Go_Inventory_Orders_Status_Enum: {waiting: '等待入库', to_inventory: '已入库'},
    Go_Inventory_Orders_Status_Array: ['等待入库','已入库'],
    Go_Inventory_Orders_To_Inventory_Warning: '选中的入库单中有已经入库的入库单!',
    Purchase_Orders_Type_Array: ['自动','手动'],
    Purchase_Orders_Status_Array: ['草稿','待询价','待审核','审核未通过','采购在途','采购在途','转为入库单','已删除'],
    Payment_method_Enum:{advance_payment: '预付款', express_collection: '快递代收', delivery_payment: '货到付款', weekly: '周结', a_half_monthly: '半月结', monthly: '月结'},
    
    Please_Type_Num: '请输入个数:',
    Please_Type_Remark: '请输入备注:',
    Create:'创建',
    Update:'更新',
    Upload:'上传',
    Close:'关闭',
    Prompt:'提示',
    Confirmation: '确认',
    Waitting: '正在加载中,请稍候.',
    Warning: '警告',
    Permissions_Reject: '权限拒绝',
    Success: '成功',
    Failure: '错误',
    Network_Error: '网络错误,请稍后再试.',
    Total_Record: '总记录',
    Result: '结果'
}